User tinyproxy
Group tinyproxy
Port 8888
Listen 0.0.0.0
Timeout 600
LogFile "/tmp/tinyproxy.log"
LogLevel Info
PidFile "/run/tinyproxy.pid"
MaxClients 100
Allow 0.0.0.0/0
DisableViaHeader Yes
ConnectPort 443
